name: Open Browser Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:              # Trigger on code push
    branches:
      - main

jobs:
  open-browser:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Puppeteer
      - name: Install Puppeteer
        run: npm install puppeteer

      # Step 4: Run Puppeteer to Open a Browser
      - name: Run Puppeteer Script
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              console.log('Launching browser...');
              const browser = await puppeteer.launch({ headless: false }); // Set headless to false for full browser
              const page = await browser.newPage();
              console.log('Navigating to GitHub...');
              await page.goto('https://github.com', { waitUntil: 'networkidle0' });
              console.log('Browser navigation complete.');
              await browser.close();
          })();
          "
