const puppeteer = require('puppeteer');

(async () => {
  try {
    console.log('Launching browser...');
    const browser = await puppeteer.launch({ headless:false }); // Set headless to false to see the browser UI
    const page = await browser.newPage();

    console.log('Navigating to GitHub...');
    await page.goto('https://github.com', { waitUntil:'networkidle0' });

    console.log('Taking a screenshot...');
    await page.screenshot({ path: 'github_homepage.png' });

    console.log('Closing browser...');
    await browser.close();
  } catch (error) {
    console.error('Error:', error);
    process.exit(1); // Exit with a failure code if an error occurs
  }
})();
